[package]
name = "transition"
version = "0.1.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2018"

[dependencies]
blinkrs = "0.2.1"
failure = "0.1.6"
crossbeam-channel = "0.4.0"
