name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libusb-1.0
      run: sudo apt-get install libusb-1.0

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Clear cargo cache # TODO: this is the workaround for https://github.com/xd009642/tarpaulin/issues/517
      run: cargo clean

    # - uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       ./target
    #       !./target/tarpaulin
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo-make
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      run: cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
